name: Manual

on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: Hello
        required: true
        description: A Cheerfull word

jobs:
  run:
    runs-on: ubuntu-lates
    steps:
      - run: echo "${{ inputs.greeting }}"
